#!/usr/bin/env python3
"""Plot the grid-convergence diagnostics generated by structured_pbe_integrity.jl.

The script intentionally sits beside ``results/`` so the published figure can
be regenerated from the numerical-verification CSV files without copying data
into the manuscript directory.  Its style parameters reproduce the clean
white-background, light-grid, blue/orange/green visual language used by the
other project-generated manuscript figures.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

# Import the shared style first: it configures Matplotlib's headless cache
# before any other Matplotlib module is loaded.
from paper_plot_style import COLOURS, add_paper_grid, apply_paper_style, plt
from matplotlib.ticker import FixedLocator, FuncFormatter, LogLocator, NullFormatter


HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"
DEFAULT_FIGURE_DIRECTORY = HERE.parent / "Draft_2026-09-07" / "figures"

def read_rows(filename: str) -> list[dict[str, str]]:
    with (RESULTS / filename).open(newline="") as handle:
        return list(csv.DictReader(handle))


def load_series() -> tuple[list[int], list[float], list[float], list[float]]:
    """Load the common diameter-CDF L-infinity convergence metric."""
    transformation = read_rows("diameter_transform_convergence.csv")
    kernels = read_rows("daughter_kernel_convergence.csv")

    nx = [int(row["nx"]) for row in transformation]
    transform_error = [float(row["cdf_linf"]) for row in transformation]
    by_kernel = {
        kernel: sorted(
            (row for row in kernels if row["kernel"] == kernel),
            key=lambda row: int(row["nx"]),
        )
        for kernel in ("biological", "hydrodynamic")
    }
    for kernel, rows in by_kernel.items():
        if [int(row["nx"]) for row in rows] != nx:
            raise ValueError(f"{kernel} kernel grid does not match transformation grid")
    return (
        nx,
        transform_error,
        [float(row["diameter_cdf_linf"]) for row in by_kernel["biological"]],
        [float(row["diameter_cdf_linf"]) for row in by_kernel["hydrodynamic"]],
    )


def format_nx(value: float, _position: int) -> str:
    return str(int(value)) if value in (32, 64, 128, 256) else ""


def plot_convergence(output_directory: Path) -> tuple[Path, Path]:
    """Create vector and high-resolution raster versions of the appendix figure."""
    apply_paper_style()
    nx, transform, biological, hydrodynamic = load_series()

    figure, axis = plt.subplots(figsize=(6.45, 3.85), layout="constrained")
    plot_options = dict(linewidth=1.8, markersize=5.5, markeredgewidth=0.75)
    axis.plot(
        nx,
        transform,
        color=COLOURS["blue"],
        marker="o",
        markeredgecolor=COLOURS["axis"],
        label="Material-to-diameter transformation",
        **plot_options,
    )
    axis.plot(
        nx,
        biological,
        color=COLOURS["orange"],
        marker="D",
        markeredgecolor=COLOURS["axis"],
        label=r"Biological daughter kernel ($N_x^{\mathrm{ref}}=512$)",
        **plot_options,
    )
    axis.plot(
        nx,
        hydrodynamic,
        color=COLOURS["green"],
        marker="^",
        markeredgecolor=COLOURS["axis"],
        label=r"Hydrodynamic daughter kernel ($N_x^{\mathrm{ref}}=512$)",
        **plot_options,
    )

    axis.set_xscale("log", base=2)
    axis.set_yscale("log")
    axis.set_xlim(28, 290)
    axis.set_ylim(1.7e-5, 0.30)
    axis.xaxis.set_major_locator(FixedLocator(nx))
    axis.xaxis.set_major_formatter(FuncFormatter(format_nx))
    axis.yaxis.set_major_locator(LogLocator(base=10.0))
    axis.yaxis.set_minor_formatter(NullFormatter())
    add_paper_grid(axis)
    axis.set_xlabel(r"Number of material sections, $N_x$")
    axis.set_ylabel(r"Diameter-CDF $L_\infty$ error")
    axis.legend(loc="lower left", handlelength=2.1)

    output_directory.mkdir(parents=True, exist_ok=True)
    pdf_path = output_directory / "fig6_numerical_integrity_convergence.pdf"
    png_path = output_directory / "fig6_numerical_integrity_convergence.png"
    figure.savefig(pdf_path, bbox_inches="tight")
    figure.savefig(png_path, bbox_inches="tight")
    plt.close(figure)
    return pdf_path, png_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_FIGURE_DIRECTORY,
        help="directory for the PDF and PNG figure",
    )
    args = parser.parse_args()
    pdf_path, png_path = plot_convergence(args.output_dir)
    print(f"Wrote {pdf_path}")
    print(f"Wrote {png_path}")


if __name__ == "__main__":
    main()
